//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtClubActivityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalantaContClub
    {
        public string ID_BalantaContClub { get; set; }
        public string ID_Username { get; set; }
        public string ID_NumeEveniment { get; set; }
        public string ID_NumeResursaResursa { get; set; }
        public string ID_Data { get; set; }
        public string Zile { get; set; }
        public string Cost { get; set; }
        public string Functie { get; set; }
    }
}
