//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtClubActivityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eveniment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eveniment()
        {
            this.Membriis = new HashSet<Membrii>();
        }
    
        public string ID_NumeEveniment { get; set; }
        public string ID_NumeResursa { get; set; }
        public string NumarZile { get; set; }
        public string ID_Data { get; set; }
        public string Ora { get; set; }
        public string ID_TipPlata { get; set; }
    
        public virtual Functie Functie { get; set; }
        public virtual Resurse Resurse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membrii> Membriis { get; set; }
    }
}
