//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtClubActivityManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtClubEntities21 : DbContext
    {
        public ArtClubEntities21()
            : base("name=ArtClubEntities21")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BalantaContClub> BalantaContClubs { get; set; }
        public virtual DbSet<Eveniment> Eveniments { get; set; }
        public virtual DbSet<Functie> Functies { get; set; }
        public virtual DbSet<Locatie> Locaties { get; set; }
        public virtual DbSet<Membrii> Membriis { get; set; }
        public virtual DbSet<Resurse> Resurses { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
