//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtClubActivityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resurse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resurse()
        {
            this.Eveniments = new HashSet<Eveniment>();
        }
    
        public string ID_NumeResursa { get; set; }
        public string ID_Locatie { get; set; }
        public string CostZi { get; set; }
        public string ID_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eveniment> Eveniments { get; set; }
        public virtual Locatie Locatie { get; set; }
        public virtual Status Status { get; set; }
    }
}
